### ISSUE TITLE
Suggested answer

### ISSUE THREAD

**Issue by rvdweerd** [niuers/Linear-Algebra-and-Learning-from-Data#1]
Dear @niuers,
Thank you for posting your solutions, they help a lot!
Can I offer one that is still work in progress? It's on section III.3, question 6 (Sylvester eq.)
![III_3_q6](https://user-images.githubusercontent.com/16600166/84439918-67095680-ac39-11ea-899a-f7d5e7f2b5dc.jpg)

**Comment by niuers** [comment]
Hi @rvdweerd , 
  Thanks very much for the suggestion. Your solution looks correct to me. Brilliant! Do you mind if I update my jupyter notebook with yours?

Thanks.

**Comment by rvdweerd** [comment]
Not at all. There might be better / simpler solutions but I can’t think of any..

**Comment by niuers** [comment]
Thanks very much. Please feel free to comment on any error I made.

**Comment by rvdweerd** [comment]
I now realize you had a much simpler and correct answer already: (AXX)X^-1 + X^-1(XXB) = C

**Comment by niuers** [comment]
I think I still need to prove that the matrices (AXX) and (XXB) are normal. That's probably why I put it in 'TODO' list.
