### ISSUE TITLE
1.9.2 Solution

### ISSUE THREAD

**Issue by sachag678** [niuers/Linear-Algebra-and-Learning-from-Data#3]
I believe there is a mistake in the solution for the closest rank-1 matrix to the matrix [[2, 1], [1, 2]].

It should be 3/2 [[1, 1], [1, 1]]. I think you left out the multiplication by the sigma term 3.

**Comment by niuers** [comment]
Fixed. thanks for point it out.

**Comment by sachag678** [comment]
No worries - Thanks for having these solutions!
